const firebaseConfig={apiKey:"AIzaSyAOf2uaP6jiF1MUp-SPkHWEGcqu5-UdM1s",authDomain:"kcfc-calendar-881f5.firebaseapp.com",databaseURL:"https://kcfc-calendar-881f5-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"kcfc-calendar-881f5",storageBucket:"kcfc-calendar-881f5.firebasestorage.app",messagingSenderId:"408090454209",appId:"1:408090454209:web:277323b24e74d58aeb8c40",measurementId:"G-47M2EMPC5Y"};
firebase.initializeApp(firebaseConfig);
const db=firebase.database(),eventsRef=db.ref("events");
let storage=null;try{storage=firebase.storage()}catch(e){console.warn("Storage unavailable",e)}
const $=id=>document.getElementById(id),fmt=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const esc=s=>{const d=document.createElement("div");d.textContent=s||"";return d.innerHTML};
let cursor=new Date(),selected=new Date(),events=[],view="month",search="";
const nameInput=$("displayName");nameInput.value=localStorage.getItem("kcfc-name")||"";nameInput.oninput=()=>localStorage.setItem("kcfc-name",nameInput.value.trim());
const theme=localStorage.getItem("kcfc-theme")||"light";document.documentElement.dataset.theme=theme;
function getName(){const n=nameInput.value.trim();if(!n){alert("先に『あなたの名前』を入力してください。");nameInput.focus();return null}return n}
function key(s){return btoa(unescape(encodeURIComponent(s))).replace(/[.#$\[\]\/]/g,"_")}
function cat(e){return e.category||"practice"}function byTime(a,b){return(a.time||"99:99").localeCompare(b.time||"99:99")}
function filtered(){const q=search.toLowerCase();return events.filter(e=>!q||[e.title,e.location,e.memo,e.createdBy].some(v=>(v||"").toLowerCase().includes(q)))}
firebase.database().ref(".info/connected").on("value",s=>{$("connectionStatus").textContent=s.val()?"● リアルタイム接続中":"○ オフライン";$("connectionStatus").classList.toggle("online",!!s.val())});
eventsRef.on("value",s=>{events=Object.entries(s.val()||{}).map(([id,v])=>({id,...v}));render()},err=>{$("connectionStatus").textContent="接続エラー：ルールを確認";console.error(err)});
function render(){renderPeriod();renderCalendar();renderList();renderDetails();scheduleNotifications()}
function renderPeriod(){$("periodTitle").textContent=view==="month"?`${cursor.getFullYear()}年 ${cursor.getMonth()+1}月`:"今後の予定一覧"}
function renderCalendar(){const grid=$("calendarGrid");grid.innerHTML="";const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,start=new Date(y,m,1-offset),list=filtered();for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const cell=document.createElement("div");cell.className="day"+(d.getMonth()!==m?" other":"")+(fmt(d)===fmt(selected)?" selected":"");const today=fmt(d)===fmt(new Date());cell.innerHTML=`<div class="day-num ${today?"today":""}"><span>${d.getDate()}</span></div>`;list.filter(e=>e.date===fmt(d)).sort(byTime).slice(0,3).forEach(e=>{const c=document.createElement("div");c.className=`chip ${cat(e)}`;c.textContent=`${e.time||""} ${e.title}`.trim();cell.appendChild(c)});const count=list.filter(e=>e.date===fmt(d)).length;if(count>3){const more=document.createElement("small");more.textContent=`ほか${count-3}件`;more.style.color="var(--muted)";cell.appendChild(more)}cell.onclick=()=>{selected=new Date(d);renderCalendar();renderDetails()};grid.appendChild(cell)}}
function renderList(){const box=$("listView");box.innerHTML="";const list=filtered().filter(e=>e.date>=fmt(new Date(new Date().setHours(0,0,0,0)))).sort((a,b)=>a.date.localeCompare(b.date)||byTime(a,b));if(!list.length){box.innerHTML='<div class="empty">今後の予定はありません</div>';return}const groups={};list.forEach(e=>(groups[e.date]??=[]).push(e));Object.entries(groups).slice(0,60).forEach(([date,items])=>{const sec=document.createElement("section");const d=new Date(date+"T00:00:00");sec.className="list-date";sec.innerHTML=`<h3>${d.getMonth()+1}月${d.getDate()}日</h3>`;items.forEach(e=>{const row=document.createElement("div");row.className=`list-item ${cat(e)}`;row.textContent=`${e.time||"時間未定"}　${e.title}${e.location?`｜${e.location}`:""}`;row.onclick=()=>{selected=d;view="month";setView();render()};sec.appendChild(row)});box.appendChild(sec)})}
function attendance(e){const g={yes:[],maybe:[],no:[]};Object.values(e.attendance||{}).forEach(v=>g[v.status]?.push(v.name));return g}
function renderDetails(){const date=fmt(selected),list=filtered().filter(e=>e.date===date).sort(byTime),d=selected;$("selectedTitle").textContent=`${d.getMonth()+1}月${d.getDate()}日の予定`;$("eventCount").textContent=`${list.length}件`;const box=$("eventList");box.innerHTML="";if(!list.length){box.innerHTML='<div class="empty">この日の予定はありません</div>';return}list.forEach(e=>{const g=attendance(e),me=nameInput.value.trim(),mine=e.attendance?.[key(me)]?.status||"";const article=document.createElement("article");article.className=`event-card ${cat(e)}-border`;article.innerHTML=`<div class="event-top"><div><h3>${esc(e.title)}</h3><p class="event-meta">${esc(e.time||"時間未定")}${e.location?`｜📍 ${esc(e.location)}`:""}</p></div><div class="card-actions"><button class="tiny edit">編集</button><button class="tiny del">削除</button></div></div>${e.memo?`<p class="event-note">${esc(e.memo)}</p>`:""}<p class="creator">追加：${esc(e.createdBy||"不明")}${e.updatedBy?`／更新：${esc(e.updatedBy)}`:""}</p>${e.attachmentUrl?`<a class="attachment" href="${esc(e.attachmentUrl)}" target="_blank" rel="noopener">📎 ${esc(e.attachmentName||"添付ファイル")}</a>`:""}<div class="attendance"><button data-s="yes" class="${mine==="yes"?"active":""}">参加 ${g.yes.length}</button><button data-s="maybe" class="${mine==="maybe"?"active":""}">未定 ${g.maybe.length}</button><button data-s="no" class="${mine==="no"?"active":""}">不参加 ${g.no.length}</button></div><div class="names">${g.yes.length?`参加：${g.yes.map(esc).join("、")}<br>`:""}${g.maybe.length?`未定：${g.maybe.map(esc).join("、")}<br>`:""}${g.no.length?`不参加：${g.no.map(esc).join("、")}`:""}${!g.yes.length&&!g.maybe.length&&!g.no.length?"まだ回答はありません":""}</div><div class="comments"><div class="comments-list">${Object.values(e.comments||{}).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0)).map(c=>`<div><b>${esc(c.name)}：</b>${esc(c.text)}</div>`).join("")||"コメントはありません"}</div><div class="comment-row"><input maxlength="180" placeholder="コメント"><button class="tiny send">送信</button></div></div>`;
article.querySelectorAll("[data-s]").forEach(b=>b.onclick=()=>setAttendance(e.id,b.dataset.s));article.querySelector(".edit").onclick=()=>openModal(e);article.querySelector(".del").onclick=()=>removeEvent(e);article.querySelector(".send").onclick=()=>addComment(e.id,article.querySelector(".comment-row input"));box.appendChild(article)})}
async function setAttendance(id,status){const n=getName();if(!n)return;await db.ref(`events/${id}/attendance/${key(n)}`).set({name:n,status,updatedAt:firebase.database.ServerValue.TIMESTAMP})}
async function addComment(id,input){const n=getName(),text=input.value.trim();if(!n||!text)return;await db.ref(`events/${id}/comments`).push({name:n,text,createdAt:firebase.database.ServerValue.TIMESTAMP});input.value=""}
async function removeEvent(e){const n=getName();if(!n)return;if(!confirm(`「${e.title}」を削除しますか？`))return;await eventsRef.child(e.id).remove()}
function openModal(e=null){const n=getName();if(!n)return;$("eventForm").reset();$("editingId").value=e?.id||"";$("formTitle").textContent=e?"予定を編集":"予定を追加";$("eventTitle").value=e?.title||"";$("eventDate").value=e?.date||fmt(selected);$("eventTime").value=e?.time||"";$("eventCategory").value=e?.category||"practice";$("eventReminder").value=String(e?.reminder||0);$("eventLocation").value=e?.location||"";$("eventMemo").value=e?.memo||"";$("uploadNote").textContent=e?.attachmentName?`現在：${e.attachmentName}`:"";$("eventModal").classList.remove("hidden");$("eventTitle").focus()}
function closeModal(){$("eventModal").classList.add("hidden")}
async function uploadFile(file,eventId){if(!file)return null;if(file.size>5*1024*1024)throw new Error("ファイルは5MB以下にしてください。");if(!storage)throw new Error("Firebase Storageが利用できません。");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const ref=storage.ref(`attachments/${eventId}/${Date.now()}_${safe}`);await ref.put(file);return{name:file.name,url:await ref.getDownloadURL()}}
$("eventForm").onsubmit=async ev=>{ev.preventDefault();const n=getName();if(!n)return;const id=$("editingId").value||eventsRef.push().key,old=events.find(e=>e.id===id)||{},payload={title:$("eventTitle").value.trim(),date:$("eventDate").value,time:$("eventTime").value,category:$("eventCategory").value,reminder:Number($("eventReminder").value),location:$("eventLocation").value.trim(),memo:$("eventMemo").value.trim(),createdBy:old.createdBy||n,createdAt:old.createdAt||firebase.database.ServerValue.TIMESTAMP,updatedBy:n,updatedAt:firebase.database.ServerValue.TIMESTAMP};const btn=ev.submitter;btn.disabled=true;btn.textContent="保存中…";try{const file=$("eventFile").files[0];if(file){$("uploadNote").textContent="添付ファイルをアップロード中…";const a=await uploadFile(file,id);payload.attachmentName=a.name;payload.attachmentUrl=a.url}else if(old.attachmentUrl){payload.attachmentName=old.attachmentName;payload.attachmentUrl=old.attachmentUrl}await eventsRef.child(id).update(payload);selected=new Date(payload.date+"T00:00:00");cursor=new Date(selected);closeModal()}catch(e){console.error(e);alert(e.message||"保存できませんでした。Firebase設定を確認してください。") }finally{btn.disabled=false;btn.textContent="保存する"}};
function setView(){document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$("monthView").classList.toggle("hidden",view!=="month");$("listView").classList.toggle("hidden",view!=="list")}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;setView();renderPeriod();renderList()});$("newEventBtn").onclick=()=>openModal();document.querySelectorAll("[data-close]").forEach(x=>x.onclick=closeModal);$("prevBtn").onclick=()=>{cursor.setMonth(cursor.getMonth()-1);render()};$("nextBtn").onclick=()=>{cursor.setMonth(cursor.getMonth()+1);render()};$("todayBtn").onclick=()=>{cursor=new Date();selected=new Date();render()};$("searchInput").oninput=e=>{search=e.target.value.trim();render()};$("themeBtn").onclick=()=>{const t=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=t;localStorage.setItem("kcfc-theme",t)};
$("notifyBtn").onclick=async()=>{if(!("Notification"in window))return alert("このブラウザは通知に対応していません。");const p=await Notification.requestPermission();alert(p==="granted"?"通知を有効にしました。サイトを開いている間に予定を確認します。":"通知が許可されませんでした。")};
const notified=new Set();function scheduleNotifications(){if(!("Notification"in window)||Notification.permission!=="granted")return;const now=Date.now();events.forEach(e=>{if(!e.time||!e.reminder)return;const at=new Date(`${e.date}T${e.time}:00`).getTime()-e.reminder*60000,k=`${e.id}-${at}`;if(at>now&&at-now<65000&&!notified.has(k)){notified.add(k);new Notification(e.title,{body:`${e.reminder}分後${e.location?`｜${e.location}`:""}`})}})}setInterval(scheduleNotifications,30000);
$("exportBtn").onclick=()=>{const lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//KCFC//Calendar//JA"];filtered().forEach(e=>{const date=e.date.replaceAll("-","");const start=e.time?`${date}T${e.time.replace(":","")}00`:`${date}`;lines.push("BEGIN:VEVENT",`UID:${e.id}@kcfc-calendar`,`DTSTART${e.time?"":";VALUE=DATE"}:${start}`,`SUMMARY:${(e.title||"").replace(/[,;\\]/g," ")}`,e.location?`LOCATION:${e.location.replace(/[,;\\]/g," ")}`:"",e.memo?`DESCRIPTION:${e.memo.replace(/\n/g,"\\n").replace(/[,;\\]/g," ")}`:"","END:VEVENT")});lines.push("END:VCALENDAR");const blob=new Blob([lines.filter(Boolean).join("\r\n")],{type:"text/calendar"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="kcfc-calendar.ics";a.click();URL.revokeObjectURL(a.href)};
setView();render();
